package com.truckexpress.Network;

public class API {
   public static String LOGIN = "http://truckexpress.live/api/Login/sendOTP";
   public static String VERIFY_OTP = "http://truckexpress.live/api/Login/verifyOTP";
   public static String BOOKINGLIST = "http://truckexpress.live/api/Booking/bookinglist";
   public static String DashboardCount = "http://truckexpress.live/api/Login/DashboardCount";
   public static String SAVEBID = "http://truckexpress.live/api/Bidding/saveBid";
   public static String Bookingshareinsert = "http://truckexpress.live/api/Bidding/Bookingshareinsert";
   public static String CHECKLIST = "http://truckexpress.live/api/Booking/checklistbooking";
   public static String CURRENTBOOKING = "http://truckexpress.live/api/Booking/currentbooking";
   public static String TripInProcess = "http://truckexpress.live/api/Booking/tripinProcess";
   public static String TripCompleted = "http://truckexpress.live/api/Booking/tripCompleted";
   public static String CORPORATEBID = "http://truckexpress.live/api/Booking/corporatebid";
   public static String Bid_Acceptedbytranspoter = "http://truckexpress.live/api/bidding/Bid_Acceptedbytranspoter";
   public static String Bidshowlog = "http://truckexpress.live/api/Booking/Bidshowlog";
   public static String RouteList = "http://truckexpress.live/api/Booking/routeList";
   public static String SaveRoutes = "http://truckexpress.live/api/Bidding/saveRoutes";
   public static String StateList = "http://truckexpress.live/api/Booking/stateList";
   public static String LunguageList = "http://truckexpress.live/api/Booking/LunguageList";
   public static String CityLists = "http://truckexpress.live/api/Booking/CityLists";
   public static String TruckTypeList = "http://truckexpress.live/api/Booking/truckTypeList";
   public static String TyresList = "http://truckexpress.live/api/Booking/tyresList";
   public static String WeightList = "http://truckexpress.live/api/Booking/weightList";
   public static String DriverList        = "http://truckexpress.live/api/Booking/DriverList";
   public static String TruckListByUserID = "http://truckexpress.live/api/Booking/TruckListbyUsierid";
   public static String TruckAssignedsave = "http://truckexpress.live/api/Bidding/TruckAssignedsave";
   public static String TruckList         = "http://truckexpress.live/api/Booking/TruckList";
   public static String SaveManualTruck = "http://truckexpress.live/api/Bidding/savemanualtruck";
   public static String ExpensesDatashow = "http://truckexpress.live/api/Booking/expensesDatashow";
   public static String GoodsTypeList = "http://truckexpress.live/api/Booking/goodsTypeList";
   public static String GoodsTypefullList = "http://truckexpress.live/api/Booking/goodsTypefullList";
   public static String UnitsList = "http://truckexpress.live/api/Booking/unitsList";
   public static String Expenselistuser = "http://truckexpress.live/api/Booking/Expenselistuser";
   public static String Checklistshow = "http://truckexpress.live/api/Booking/Checklistshow";
   public static String ChecklistInsert = "http://truckexpress.live/api/Bidding/Transporterschecklistinsert";
   public static String ExpanseInsert = "http://truckexpress.live/api/Bidding/Expanseinsert";
   public static String Transportersgoodtype = "http://truckexpress.live/api/Bidding/Transportersgoodtype";
   public static String BankList = "http://truckexpress.live/api/booking/banklist";
   public static String BranchName = "http://truckexpress.live/api/booking/branchname";
   public static String UploadImageDriver = "http://truckexpress.live/api/UploadImageDriver";
   public static String UploadImageMotorOwner = "http://truckexpress.live/api/UploadImageMotorOwner";
   public static String UploadImage = "http://truckexpress.live/api/UploadImage";
   public static String BookingReasonInsert = "http://truckexpress.live/api/Bidding/Bookingreasoninsert";
   public static String DestinationList = "http://truckexpress.live/api/Booking/DestinationList";
   public static String SourceList = "http://truckexpress.live/api/Booking/SourceList";
   public static String MoterOwnerList = "http://truckexpress.live/api/Booking/MoterOwnerList";
   public static String RouteMotorOwnerList = "http://truckexpress.live/api/Booking/RouteMotorOwnerList";
   public static String Bookingshareexpensesfinalinsert = "http://truckexpress.live/api/Bidding/Bookingshareexpensesfinalinsert";
   public static String LoadingTrucklist = "http://truckexpress.live/api/Booking/LoadingTrucklist";
   public static String LoadedTruck = "http://truckexpress.live/api/Booking/LoadedTruck";
   public static String UnloadedTrucklist = "http://truckexpress.live/api/Booking/UnloadedTrucklist";
   public static String addArrival = "http://truckexpress.live/api/Bidding/savetruckarrival";
   public static String apploading = "http://truckexpress.live/api/Bidding/saveloading";
   public static String saveunloading = "http://truckexpress.live/api/Bidding/saveunloading";
   public static String canceltruckassigned = "http://truckexpress.live/api/Bidding/canceltruckassigned";
   public static String truckcount = "http://truckexpress.live/api/Booking/truckcount";
   public static String sumweight = "http://truckexpress.live/api/Booking/sumweight";
   public static String loadedcountandsumtruck = "http://truckexpress.live/api/Booking/loadedcountandsumtruck";


}
